name: 'Run Nook Viewer Script'
description: 'Clones the nook repository and runs the vierer.py script'
runs:
  using: 'composite'
  steps:
    - name: Clone repository
      run: |
        git clone https://github.com/masahito-uwamichi/nook.git
      shell: bash
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: nook
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r nook/functions/viewer/requirements.txt
      shell: bash

    - name: Start FastAPI server
      run: |
        export PYTHONPATH=$(pwd)/nook
        nohup uvicorn nook.functions.viewer.viewer:app --host 0.0.0.0 --port 8000 & # python nook/nook/functions/viewer/viewer.py 
        sleep 1200  # Run for 20 minutes (1200 seconds)
      shell: bash
