name: 'Run Nook Viewer Script'
description: 'Clones the nook repository and runs the vierer.py script'
inputs:
  ngrok_auth_token:
    description: 'NGrok Authentication Token'
    required: True
runs:
  using: 'composite'
  steps:
    - name: Clone repository
      run: |
        git clone https://github.com/masahito-uwamichi/nook.git
      shell: bash
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      working-directory: nook
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r nook/functions/viewer/requirements.txt
      shell: bash

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq
        curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
        echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
        sudo apt-get update
        sudo apt-get install ngrok
      shell: bash

    - name: Start ngrok
      run: |
        ngrok config add-authtoken ${{ inputs.ngrok_auth_token }}
        #ngrok http 80
      shell: bash

    - name: Start FastAPI server
      run: |
        export PYTHONPATH=$(pwd)/nook
        nohup uvicorn nook.functions.viewer.viewer:app --host 0.0.0.0 --port 8000 &
        ngrok http 8000 > /dev/null &
        sleep 5
        curl -s http://localhost:4040/api/tunnels | jq -r .tunnels[0].public_url
        sleep 1200  # Run for 20 minutes (1200 seconds)
      shell: bash
