name: 'Run Nook Main Script'
description: 'Clones the nook repository and runs the main.py script'
inputs:
  gemini_api_key:
    description: 'Gemini API key'
    required: true
  reddit_client_id:
    description: 'Reddit client ID'
    required: true
  reddit_client_secret:
    description: 'Reddit client secret'
    required: true
  reddit_user_agent:
    description: 'Reddit user agent'
    required: true
  output_dir:
    description: 'Output directory'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Clone repository
      run: |
        git clone https://github.com/masahito-uwamichi/nook.git
      shell: bash
      
    - name: Install dependencies
      working-directory: nook
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
      shell: bash

    - name: Run script
      working-directory: nook
      env:
        GEMINI_API_KEY: ${{ inputs.gemini_api_key }}
        REDDIT_CLIENT_ID: ${{ inputs.reddit_client_id }}
        REDDIT_CLIENT_SECRET: ${{ inputs.reddit_client_secret }}
        REDDIT_USER_AGENT: ${{ inputs.reddit_user_agent }}
        OUTPUT_DIR: ${{ inputs.output_dir }}
      run: |
        python main.py
      shell: bash
